apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: redis
      app: redis
    includeTemplates: true

resources:
- redis-deployment.yaml
- redis-service.yaml