apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <NAMESPACE_PLACEHOLDER>

sortOptions:
  legacySortOptions:
    orderFirst:
    - ServiceAccount
    - RoleBinding
    - ConfigMap
    - Secret
    - ImageStream
    - BuildConfig
    - PersistentVolumeClaim
    - Deployment
    - Service
    - Route
  order: legacy

resources:
- mcp-context-forge
# - redis

# There is an issue to use Postgresql and Mariadb/MySQL with mcp-context-forge in OpenShift on Power
# Just change to use SQLite
# - postgresql
# - mariadb